### ISSUE TITLE
wf.watchApiGateway('Some API', api) errors with Cannot read property 'stageName' of undefined

### ISSUE THREAD

**Issue by kpapagno** [cdklabs/cdk-watchful#464]
I have a RestAPI  which is defined with a deploy: false flag.   I then add various methods to the api, and finally create 2 deployment stages DEV, and QA with API keys.   That all works fine.

When I added the code:
```
    const wf = new Watchful(this, 'monitoring', {
      alarmEmail: 'myemail@address',
    });
    wf.watchLambdaFunction('Lambda watcher', lambdaHandler);
    wf.watchApiGateway('My API', api);
```
I get a message at deploy time:
```
Cannot read property 'stageName' of undefined
Subprocess exited with error 1
```
If I **comment out** the **watchApigateway** it proceeds as expected, but only builds dashboard for Lambda.   
Are there restrictions on API Gateway?    

I also tried defining the api as `
const existingAPI = apigateway.RestApi.fromRestApiId(this, 'existingAPI', api.restApiId);`
but the watchApiGateway doesn't support the IRestApi, only RestAPI.

Am I missing something?   Thanks

Ken

**Comment by ayush987goyal** [comment]
For configuring the monitoring/dashboards for api gateway, we use the `stageName` from `deploymentStage` of the provided api. If you do not set the `deploy` flag as `true`, the default deployment stage is not created. Since you have manually created  deployment stage for your api, you probably need to assign it like so

```ts
api.deploymentStage = myStage;
```

Doing that would make the `deploymentStage` property available and hence `stageName` too. Let me know if doing that fixes the issue.

**Comment by kpapagno** [comment]
Thank you!  That worked great!
