### ISSUE TITLE
RestApi.fromRestApiId doesn't work 

### ISSUE THREAD

**Issue by seawatts** [cdklabs/cdk-watchful#7]
When I try to import a rest Api and then pass it into `watchApiGateway` it throws an error `No child with path: 'Resource'`

https://github.com/eladb/cdk-watchful/blob/master/lib/api-gateway.ts#L54

**Comment by BenChaimberg** [comment]
Since API Gateway metrics require the API name as a dimension, which is not supplied by either of the import methods (the name will [default to the construct ID](https://github.com/aws/aws-cdk/blob/ff044eddccfe1e4812e686343ca1a614b73a1a1f/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L323), which obviously has no tie to the actual name), an imported API cannot reliably be used to create metrics.
